version: "3.9"
services:
  db:
    restart: always
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
       MYSQL_DATABASE: 'django'
       MYSQL_USER: 'djangouser'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password123'
    ports:
      - "3306:3306"
    networks:
      - db-net

  backend:
    restart: always
    container_name: back
    entrypoint: /app/docker/backend/wsgi-entrypoint.sh
    volumes:
      - ./backend/:/app/backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    expose:
      - 8000 
    depends_on:
      - db
    networks:
      - db-net

  frontend:
    restart: always
    container_name: front
    volumes:
      - ./frontend/:/app/frontend
      - ./docker/nginx/development:/etc/nginx/conf.d
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    stdin_open: true
    depends_on:
      - backend
    networks:
      - db-net

networks:
  db-net:
    driver: bridge

